# Generated by Django 4.1 on 2022-08-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataEnglish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nguoiDung', models.CharField(max_length=100)),
                ('ExerciseChoose', models.CharField(max_length=100)),
                ('TopicChoose', models.TextField()),
            ],
        ),
    ]
