# Generated by Django 4.1 on 2022-08-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_khoahoc_delete_dataenglish'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerDataEnglish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataJson', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='khoaHoc',
        ),
    ]
